	PROGRAM DIRREFLEC
	IMPLICIT REAL*8 (A-H,O-Z)
	WRITE(*,5)
   5	FORMAT(5X,'INPUT INDEX OF REFRACTION: N,K')
	READ(*,*) AN,AK
	WRITE(6,6) AN,AK
   6	FORMAT(5X,'N =',F5.2,',  K =',F5.2//)
	WRITE(*,7)
   7	FORMAT(5X,'INPUT SPACING FOR OUTPUT, IN DEGREES')
	READ(*,*) ISTEP
	WRITE(6,8)
   8	FORMAT(5X,'THETA     RHOS      RHOP      RHO       EPS')
	PI2=2.D0*DATAN(1.D0)
	DO 10 I=1,91,ISTEP
	TH=(I-1)*PI2/9.D1
	PH=(I-1)
	CALL FRESNEL(AN,AK,TH,RHOS,RHOP,RHO)
	EPS=1.D0-RHO
	WRITE(6,20) PH,RHOS,RHOP,RHO,EPS
  20  FORMAT(F10.0,4F10.4)
  10	CONTINUE
	STOP
	END
	SUBROUTINE FRESNEL(AN,AK,TH,RHOS,RHOP,RHO)
	IMPLICIT REAL*8 (A-H,O-Z)
	C1=AN*AN-AK*AK-DSIN(TH)**2
	P2=.5D0*(DSQRT(C1*C1+(2.D0*AN*AK)**2)+C1)
	Q2=P2-C1
	CT=DCOS(TH)
	C2=(AN*AN-AK*AK)*CT
	C3=2.D0*AN*AK*CT
	P=DSQRT(P2)
	Q=DSQRT(Q2)
	RHOP=((P-C2)**2+(Q-C3)**2)/((P+C2)**2+(Q+C3)**2)
	RHOS=((CT-P)**2+Q2)/((CT+P)**2+Q2)
	RHO=.5D0*(RHOP+RHOS)
	RETURN
	END

	
